### ISSUE TITLE
Artık çalışmıyor

### ISSUE THREAD

**Issue by erenseymen** [muratcorlu/eksirss#10]
Selamlar. 3 haftadır çalışmadığını yeni fark ettim. Bilginize.

**Comment by muratcorlu** [comment]
Haber verdiğin için teşekkürler. İlk incelememde sebebini çözemedim. Daha ayrıntılı bakıp çözmeye çalışacağım.

**Comment by erenseymen** [comment]
Tekrar çalışmaya başladı.
