### ISSUE TITLE
Ekşi'de olmayan başlıkların ele alınması

### ISSUE THREAD

**Issue by muratcorlu** [muratcorlu/eksirss#2]
Ekşisözlük'te olmayan bir başlık girildiğinde bu konuda bir bilgilendirme yapılmalı

**Comment by cenkingunlugu** [comment]
form postu javascript ile yapip uretilen url i json olarak karsi taraftan alarak ekstra data ile bu basligin eksi sozlukte var olup olmadigini bu anda kullaniciya bildirmek gibi bir yontem mi dusunuyorsun?

**Comment by muratcorlu** [comment]
Aslında bu kadar uzun uzadıya bir çözüm düşünmedim. Şu an olmayan bir başlık ararsan 500 hatası veriyor. İnsancıl bir hata sayfası göstersek yeterli.

**Comment by mpaltun** [comment]
500 hatasi vermiyor sanki ?

**Comment by mpaltun** [comment]
Bu sekil uygun mudur ?

https://github.com/muratcorlu/eksirss/commit/b4797be2e903af850e03445eeda9cbabb33f14ad#diff-5bc02cefb3ea9e27f1a6776eabd1935dR195

**Comment by muratcorlu** [comment]
Tamamdır, hata vermiyormuş zaten. Cannot reproduce :)
