### ISSUE TITLE
Güncellenmeyen RSS başlıkları

### ISSUE THREAD

**Issue by sozcelyk** [muratcorlu/eksirss#3]
Merhaba,

Kontrol ediyorum uzun zamandır uygulamayı. Bazı başlıkların bir hafta kadar geride kaldığını görüyorum. Neden olabilir? 

Geride kalmış RSS: https://eksirss.muratcorlu.com/feed/?t=gss%20prim%20borcu
Ekşi: https://eksisozluk.com/gss-prim-borcu--3557449?a=tracked&snapshot=65442192

Geride kalmış RSS:  https://eksirss.muratcorlu.com/feed/?t=bein%20sports
Ekşi: https://eksisozluk.com/bein-sports--4719236?a=tracked&snapshot=65551734 

Örnekler daha da çoğaltılabilir.

**Comment by muratcorlu** [comment]
@mpaltun periyodik fetch ederken yeni sayfa eklenmiş mi diye kontrol etmiyoruz sanırım? Bana bundan kaynaklanıyor olabilir gibi geldi. Hatta geçen böyle bir problem olabilir diye aklıma geldi ama kodu incelerken işim çıktı ayrıntılı bakamadım.

**Comment by mpaltun** [comment]
Yok abi ediyoruz ama yeni sayfayi url'e ekliyoruz gibi duruyor. Yani olusan url `?p=5&p=6` halini aliyor. Eksi de ilk p'yi aliyor muhtemelen. Bu yuzden daha yeni sayfaya gidemiyoruz.

**Comment by mpaltun** [comment]
b6f1f6ae7123d444089590906156cc1bba0b27a5  ile cozuldu.

**Comment by sozcelyk** [comment]
Yeni entry'ler hala rss'e gelmemiş görünüyor.  Bir de ne kadarlık cache var acaba? Yani yeni entry'lerin gelmesini ne kadar süre beklemeliyiz?

https://eksirss.muratcorlu.com/feed/?t=bein%20sports 
https://eksisozluk.com/bein-sports--4719236?a=tracked&snapshot=65645977

**Comment by muratcorlu** [comment]
Acaba mevcut url'ler düzelmiyor mu bu çözümle? @mpaltun datastore'daki url'e baksana
<img width="379" alt="screen shot 2017-01-18 at 14 53 22" src="https://cloud.githubusercontent.com/assets/127687/22063070/9632f1f4-dd85-11e6-98db-51b36231649c.png">

**Comment by muratcorlu** [comment]
bein sports başlığının url'ini elle düzelttim. Problem bundan kaynaklıysa sıradaki fetch'de düzelmesini bekliyorum. Düzelirse bütün mevcut kayıtların url'lerini elle düzeltiriz belki.

**Comment by sozcelyk** [comment]
Ben bir süre izleyeyim Bein başlığı düzeldi mi acaba diye. 

Eğer düzeldiyse ben de mevcut kayıtlı URL'leri manuel düzenleme konusunda yardımcı olabilirim. Hangi dosyada nereyi düzeltmemiz gerektiğini söylerseniz tabi :)

**Comment by muratcorlu** [comment]
Hehe, teşekkürler. Elle dediğime bakmayın, muhtemelen küçük bir kod yazar öyle değiştiririz zaten :)

**Comment by muratcorlu** [comment]
`'9' > '16'` True veriyordu. Bundan sanırım.

**Comment by sozcelyk** [comment]
düzelmiş bein başlığı :)

**Comment by muratcorlu** [comment]
Şu url'i &p=3&p=4 gibi kayıtlı olan diğer kayıtlarda da durumun düzeldiğinden emin olunca işi kapatalım.

**Comment by muratcorlu** [comment]
Şu başlıkta url hala biraz garip mesela. Bu düzelecek mi bakalım.
![image](https://cloud.githubusercontent.com/assets/127687/22072616/973fd636-ddab-11e6-9240-41ace6751a44.png)

**Comment by muratcorlu** [comment]
Bu başlık da düzelmiş. Sanırım çözdük. İşi kapatıyorum.

**Comment by sozcelyk** [comment]
Hitler başlığına bugün girilen son entry de geldi.

Elinize sağlık ;)
