### ISSUE TITLE
Ekşideki başlık sayfa sayısı düşünce yeni entryler çekilmiyor

### ISSUE THREAD

**Issue by muratcorlu** [muratcorlu/eksirss#4]
İlginç bir durum olmuş. Data Store'da şöyle bir kayıt var:

![image](https://cloud.githubusercontent.com/assets/127687/22115420/95188414-de75-11e6-943b-6fcfa0db00e9.png)

URL'de `p=3975` diyor ancak o başlıkta şu anda 3971 sayfa var. 3975'inci sayfayı çağırınca da boş sayfa geliyor, o yüzden bu sayfaya gelene kadar entryler çekilemeyecek gibi görünüyor. :)

Sanırım şu son sayfaya mı bakıyoruz kontrolüne bu istisnai durumu da eklemek lazım.

**Comment by cenkingunlugu** [comment]
Son cache deletionları dikkate almıyor sanırım. Cache süresini düşürmek çözebilir

**Comment by muratcorlu** [comment]
Yok şurada sadece sayfanın artmış olma ihtimalini değerlendiriyoruz: https://github.com/muratcorlu/eksirss/blob/master/main.py#L96

Sayfa sayısının düşmüş olması durumunda aktif sayfa numarasını bu son sayfa sayısına eşitlemek lazım. Halledicem sanırım :)

**Comment by muratcorlu** [comment]
`if int(last_page_number) != int(current_page_number):` bu çözer bence

**Comment by mpaltun** [comment]
<img width="663" alt="screen shot 2017-01-19 at 19 33 15" src="https://cloud.githubusercontent.com/assets/494111/22117947/881f59a0-de7e-11e6-904c-08fc49494cc2.png">

Cozmez abi. Cunku sayfa bos geliyor ve elimizde paging bilgisi yok. Bence entry sayisini alip 10'a bolerek sayfa sayisini bulabiliriz :)

**Comment by muratcorlu** [comment]
Hımm, o zaman işi tekrar açalım. :)

**Comment by sozcelyk** [comment]
Bu konuyla mı alakalı emin değilim ama onlarca entry olmasına rağmen şu rss uzun zamandır çalışmıyor.

https://eksirss.muratcorlu.com/feed/?t=spotify

**Comment by muratcorlu** [comment]
Kontrol edeceğim.

**Comment by muratcorlu** [comment]
@mpaltun commit için teşekkürler. ama şu spotify başlığında başka bir sorun var gibi. 18 Ocak'tan beri güncellenmemiş görünüyor kaydı. last_update_date 18 ocak yani. Onun gibi bi 20-30 başlık daha var, 18 ocakta kalmışlar. Neden olabilir bilemedim.

**Comment by muratcorlu** [comment]
Son commit'le spotify başlığındaki problem de giderilmiş gibi görünüyor. İşi kapatıyorum.
