### ISSUE TITLE
Entry'deki boşluk ve linklerin çalışmaması konusu

### ISSUE THREAD

**Issue by sozcelyk** [muratcorlu/eksirss#5]
Merhaba,

Kullanmış olduğum bir bot, RSS'ler üzerinden data çekiyor ancak rss'teki BR taglarını ve linkleri doğru şekilde parse edemiyor. Bunun sebebinin de rss'in hiçbir html elementini vermemesi, sadece description'u vermesi olduğunu söylüyorlar. 

Çözüm olarak da, ''HTML'i CDATA bölümündeki açıklama etiketlerine yerleştirilmelidir'' diyorlar. 

RSS'ten alınan içerik böyle görünüyor. Kırmızı ile çizdiğim yerde boşluk olması lazım normalde: http://prntscr.com/dy41nw

RSS'te o alanda BR tagı var aslında. https://eksirss.muratcorlu.com/feed/?t=google%20pixel   SS: http://prntscr.com/dy426j 

Çözülebilir bir şey mi acaba bu ?

**Comment by muratcorlu** [comment]
Ekran görüntüsünde linki parse ettiği görünüyor aslında. br'leri normalize ediyor olmasın? Genelde rss reader'lar özet bölümünde açıklamaları tek paragraf göstermeye çalışır.

**Comment by sozcelyk** [comment]
link geliyor ama şu şekilde geliyor. bu botla mi alakalı yoksa rss ile mi alakalı bilemedim. link : http://www.theverge.com/%E2%80%A6hone-shipping-out-of-stockgibi    ekran görüntüsü : https://goo.gl/photos/svQgmxuGs5wGeBrA7

br ile ilgili de bot sahibi şöyle bir yorum yapmış.

the problem is not BR, but the whole "description" section in the RSS feed.
The HTML in that section should be embedded in a CDATA section; otherwise it's not a valid XML/RSS file...

**Comment by muratcorlu** [comment]
CDATA konusunda haklı olabilir. Bakalım

**Comment by sozcelyk** [comment]
şöyle de bir test yapmış . belki yardımcı olabilir. 

https://goo.gl/photos/p1WmJzFzNYeKfKuq7

**Comment by muratcorlu** [comment]
CDATA ekledim, yayına aldım. Cache'ler yenilendikçe etkisini takip edelim.

**Comment by sozcelyk** [comment]
çoook teşekkürler, çalışıyor :))) https://goo.gl/photos/xzKV33Nw6VMNmTmW9

linklerin doğru çalışmaması konusu diğer issue'dan takip ediliyor sanırım.

**Comment by muratcorlu** [comment]
Evet linkler için yarı iş açtım. Teşekkürler
