### ISSUE TITLE
çok fazla entry girilen başlıklarda tüm entry'lerin çekilmemesi

### ISSUE THREAD

**Issue by sozcelyk** [muratcorlu/eksirss#8]
merhaba, bir süredir fark ediyorum eğer bir başlığa iki günde 300-400 entry giriliyorsa, bu entry'lerin en az yarısı rss olarak gelmiyor.

örneğin  bu başlık için 300 civarı entry girilmiş ik, günde ama rss bunların yarısını bile çekmemiş.

https://eksisozluk.com/whatsapp--2239546 

https://eksirss.muratcorlu.com/feed/?t=whatsapp

**Comment by muratcorlu** [comment]
Bu zor bir konu. Anlık olarak ekşiden entryleri alamadığımız için aralarda kaçan entryler kaçınılmaz maalesef. Şu anda yaklaşık 1.5-2 saatte bir bakılıyor başlıklara. Ve bakıldığı andaki son 10 entry alınıyor. Popüler başlıklarda kaçan içerik çok oluyor tabi.

**Comment by sozcelyk** [comment]
anladım. 2 saatte bir çekilen entry sayısını 10'dan 40-50'ye vs çıkarmak sunucuya daha fazla yük binmesi demek olduğu için mi limit 10 ? yapacak bir şey yok o zaman.

**Comment by muratcorlu** [comment]
Yani, şu an projenin masraf çıkartmaması için optimizasyonun diplerinde dolaşıyoruz. Bir gelir olmadığından daha fazlasına inmek biraz riskli ve gereksiz görünüyor bizim için. Zaten ekşisözlük küçücük bir eforla başlıklara rss desteği verse proje şu anki haliyle anında çöp olur :)

**Comment by sozcelyk** [comment]
Tamamdır ben de onu anlamaya çalışmıştım. Şu hali de tıkır tıkır çalışıyor zaten elinize sağlık :)
