### ISSUE TITLE
Datastore read/write sayılarını azaltma

### ISSUE THREAD

**Issue by muratcorlu** [muratcorlu/eksirss#9]
Datastore'un günlük ücretsiz yazma kotası 20k, okuma kotası da 50k. Şu anda günde yaklaşık 80k write, 80k da read yapıyoruz. Bu sayıları kota içerisinde tutabilirsek projenin masraf çıkarmasını engeleyebiliriz. :)

Bazı şeyler için Memcached kullanımını biraz daha artırmak bir çözüm olabilir.

**Comment by muratcorlu** [comment]
Şurada key oluştururken Datastore'a bir request yapmış oluyor muyuz emin olamadım: https://github.com/muratcorlu/eksirss/blob/master/main.py#L51

Bir de her requestte son request süresini update ediyoruz datastore'da. Belki bu veriyi datastore yerine aynı keyle memcache üzerinde tutmak faydalı olabilir.

**Comment by mpaltun** [comment]
Yapmiyoruz orada request. 
last_hit alanini cache'de tutacak sekilde degisiklik yaptim, bakalim neler olacak.

**Comment by muratcorlu** [comment]
Bu hareket read ve write'ları 50k'ya düşürdü. Yazma kotasında hala ilerideyiz. Günde 50 write'ı nerede yapıyoruz anlamadım.

**Comment by mpaltun** [comment]
Su anda gunluk yazma sayisi 10k civarinda, cozulmus duruyor.
